### ISSUE TITLE
Problems from python arithmetic section

### ISSUE THREAD

**Issue by xu932** [PurdueCAM2Project/SE4ML#1]
On page 22 of the book (or line 222-229 in `software/python/python.tex`) The section shows following:
```
>>> 20
20
>>> 020
20
>>> 0x20
16
```
When I tried do to the same in an interactive session with Python 3.4.1 and 3.7.0, this is what I got as the output:
```
>>> 20
20
>>> 020
File "<stdin>", line 1
    020
      ^
SyntaxError: invalid token
>>> 0x20
32
```
And when I tried with Python 2.7.0, this is what I got:
```
>>> 20
20
>>> 020
16
>>> 0x20
32
```
Out of three versions I have tried, neither give an output of `16` when `0x20` is typed. Output for `020` is different across different versions. Can the python version be included in the book?

**Comment by anivegesana** [comment]
In Python 3, it was changed to `0o20` to prevent confusion among beginning programmers.

**Comment by anivegesana** [comment]
I also found that long integers do not exist in Python 3. `2L` will give an error because the Python 3 `int` is different and allows for a much wider range of values than just 32 bits or 64 bits: https://www.python.org/dev/peps/pep-0237/.

**Comment by gkthiruvathukal** [comment]
Excellent catches @xu932 and @anivegesana. These are, indeed, holdovers from Python 2. We are moving entirely to Python 3, so I will correct these.
