### ISSUE TITLE
Possible typo on page 27?

### ISSUE THREAD

**Issue by xu932** [PurdueCAM2Project/SE4ML#2]
On page 27 of the book (or line 513-519 in `/software/python/python.tex`), the section shows:
```
>>> def diff(x,y):
...    return abs(x-y)
...
>>> diff(-10.5)
15
```
Which I believe the function call should be `diff(-10,5)` instead of `diff(-10.5)` where one takes two arguments and what is shown only takes one argument.

**Comment by gkthiruvathukal** [comment]
Thanks for reporting this @xu932. We are moving the book to Sphinx, so I am only correcting the issue there for now.  Take a look at https://se4ml.org for a preview.
